device: cuda:2
model: resnet18
data_code: cifar10
num_classes: 10

epochs: 300
batch_size: 128
optimizer: sgd
lr_scheduler : default
learning_rate: 0.01
seed: 1234

sparsity_type: kernel
prune_ratio: 0.7
admm: True
admm_epochs: 300
rho: 0.0001
multi_rho: True
retrain_bs: 128
retrain_lr: 0.001
retrain_ep: 100
retrain_opt: default

xentropy_weight: 1.

warmup : False
warmup_lr :  0.001
warmup_epochs :  10
mix_up :  True
alpha :  0.3
smooth :  False
smooth_eps :  0
save_last_model_only: False

num_partition: 4
layer_type: regular
bn_type: masked

par_first_layer: True
comm_outsize: True
lambda_comm: 0.0001
lambda_comp: 0
create_partition: False
load_model: True