device: cuda:0
# model: wrn28_10
model: resnet101
data_code: cifar100
num_classes: 100

epochs: 300
batch_size: 128
optimizer: sgd
lr_scheduler: default
learning_rate: 0.1
seed: 1234

sparsity_type: kernel
prune_ratio: 0.5
admm: True
admm_epochs: 300
rho: 0.0001
multi_rho: True
retrain_bs: 128
retrain_lr: 0.01
retrain_ep: 100
retrain_opt: default

xentropy_weight: 1.

warmup : False
warmup_lr :  0.01
warmup_epochs :  10
mix_up :  True
alpha :  0.3
smooth :  False
smooth_eps :  0
save_last_model_only: False

num_partition: 4
layer_type: regular
bn_type: masked

par_first_layer: True
comm_outsize: True
lambda_comm: 0.0001
lambda_comp: 0
create_partition: False
load_dense_model: True
load_pruned_model: False