device: cuda:1
model: EscFusion
data_code: esc
num_classes: 2

epochs: 10
batch_size: 32
optimizer: adam
lr_scheduler: cosine
learning_rate: 0.01
seed: 1234

sparsity_type: kernel
prune_ratio: 0.8
admm: True
admm_epochs: 300
rho: 0.01
multi_rho: True
retrain_bs: 128
retrain_lr: 0.001
retrain_ep: 100
retrain_opt: adam

xentropy_weight: 1.

warmup : False
warmup_lr :  0.01
warmup_epochs :  10
mix_up : True
alpha :  0.3
smooth :  False
smooth_eps :  0
save_last_model_only: False

num_partition: 4
layer_type: regular
bn_type: regular

par_first_layer: True
comm_outsize: True
lambda_comm: 1000
lambda_comp: 0
create_partition: False
load_model: True
