bn_partitions: [1, 1, 1, 1, 1, 1, 1, 1, 1]
maps:
  conv1.weight: [[0]]
  conv2.weight: [[0]]
  inputs: [[0]]
  layer1.0.conv1.weight: [[0]]
  layer1.0.conv2.weight: [[0]]
  layer2.0.conv1.weight: [[0]]
  layer2.0.conv2.weight: [[0]]
  linear1.weight: [[0]]
  linear2.weight: [[0]]
partitions:
  conv1.weight: [1]
  conv2.weight: [1]
  inputs: [1]
  layer1.0.conv1.weight: [1]
  layer1.0.conv2.weight: [1]
  layer2.0.conv1.weight: [1]
  layer2.0.conv2.weight: [1]
  linear1.weight: [1]
  linear2.weight: [1]
