bn_partitions: [2, 2, 2, 2, 2, 2, 2, 2, 2]
maps:
  conv1.weight: [[0, 1], [1, 0]]
  inputs: [[0, 1], [1, 0]]
  layer1.0.conv1.weight: [[0, 1], [1, 0]]
  layer1.0.conv2.weight: [[0, 1], [1, 0]]
  layer1.1.conv1.weight: [[0, 1], [1, 0]]
  layer1.1.conv2.weight: [[0, 1], [1, 0]]
  layer1.2.conv1.weight: [[0, 1], [1, 0]]
  layer1.2.conv2.weight: [[0, 1], [1, 0]]
  layer2.0.conv1.weight: [[0, 1], [1, 0]]
  layer2.0.conv2.weight: [[0, 1], [1, 0]]
  layer2.0.shortcut.0.weight: [[0, 1], [1, 0]]
  layer2.1.conv1.weight: [[0, 1], [1, 0]]
  layer2.1.conv2.weight: [[0, 1], [1, 0]]
  layer2.2.conv1.weight: [[0, 1], [1, 0]]
  layer2.2.conv2.weight: [[0, 1], [1, 0]]
  layer2.3.conv1.weight: [[0, 1], [1, 0]]
  layer2.3.conv2.weight: [[0, 1], [1, 0]]
  layer3.0.conv1.weight: [[0, 1], [1, 0]]
  layer3.0.conv2.weight: [[0, 1], [1, 0]]
  layer3.0.shortcut.0.weight: [[0, 1], [1, 0]]
  layer3.1.conv1.weight: [[0, 1], [1, 0]]
  layer3.1.conv2.weight: [[0, 1], [1, 0]]
  layer3.10.conv1.weight: [[0, 1], [1, 0]]
  layer3.10.conv2.weight: [[0, 1], [1, 0]]
  layer3.11.conv1.weight: [[0, 1], [1, 0]]
  layer3.11.conv2.weight: [[0, 1], [1, 0]]
  layer3.12.conv1.weight: [[0, 1], [1, 0]]
  layer3.12.conv2.weight: [[0, 1], [1, 0]]
  layer3.13.conv1.weight: [[0, 1], [1, 0]]
  layer3.13.conv2.weight: [[0, 1], [1, 0]]
  layer3.14.conv1.weight: [[0, 1], [1, 0]]
  layer3.14.conv2.weight: [[0, 1], [1, 0]]
  layer3.15.conv1.weight: [[0, 1], [1, 0]]
  layer3.15.conv2.weight: [[0, 1], [1, 0]]
  layer3.16.conv1.weight: [[0, 1], [1, 0]]
  layer3.16.conv2.weight: [[0, 1], [1, 0]]
  layer3.17.conv1.weight: [[0, 1], [1, 0]]
  layer3.17.conv2.weight: [[0, 1], [1, 0]]
  layer3.18.conv1.weight: [[0, 1], [1, 0]]
  layer3.18.conv2.weight: [[0, 1], [1, 0]]
  layer3.19.conv1.weight: [[0, 1], [1, 0]]
  layer3.19.conv2.weight: [[0, 1], [1, 0]]
  layer3.2.conv1.weight: [[0, 1], [1, 0]]
  layer3.2.conv2.weight: [[0, 1], [1, 0]]
  layer3.20.conv1.weight: [[0, 1], [1, 0]]
  layer3.20.conv2.weight: [[0, 1], [1, 0]]
  layer3.21.conv1.weight: [[0, 1], [1, 0]]
  layer3.21.conv2.weight: [[0, 1], [1, 0]]
  layer3.22.conv1.weight: [[0, 1], [1, 0]]
  layer3.22.conv2.weight: [[0, 1], [1, 0]]
  layer3.3.conv1.weight: [[0, 1], [1, 0]]
  layer3.3.conv2.weight: [[0, 1], [1, 0]]
  layer3.4.conv1.weight: [[0, 1], [1, 0]]
  layer3.4.conv2.weight: [[0, 1], [1, 0]]
  layer3.5.conv1.weight: [[0, 1], [1, 0]]
  layer3.5.conv2.weight: [[0, 1], [1, 0]]
  layer3.6.conv1.weight: [[0, 1], [1, 0]]
  layer3.6.conv2.weight: [[0, 1], [1, 0]]
  layer3.7.conv1.weight: [[0, 1], [1, 0]]
  layer3.7.conv2.weight: [[0, 1], [1, 0]]
  layer3.8.conv1.weight: [[0, 1], [1, 0]]
  layer3.8.conv2.weight: [[0, 1], [1, 0]]
  layer3.9.conv1.weight: [[0, 1], [1, 0]]
  layer3.9.conv2.weight: [[0, 1], [1, 0]]
  layer4.0.conv1.weight: [[0, 1], [1, 0]]
  layer4.0.conv2.weight: [[0, 1], [1, 0]]
  layer4.0.shortcut.0.weight: [[0, 1], [1, 0]]
  layer4.1.conv1.weight: [[0, 1], [1, 0]]
  layer4.1.conv2.weight: [[0, 1], [1, 0]]
  layer4.2.conv1.weight: [[0, 1], [1, 0]]
  layer4.2.conv2.weight: [[0, 1], [1, 0]]
partitions:
  conv1.weight: [1, 1]
  inputs: [1, 1]
  layer1.0.conv1.weight: [1, 1]
  layer1.0.conv2.weight: [1, 1]
  layer1.1.conv1.weight: [1, 1]
  layer1.1.conv2.weight: [1, 1]
  layer1.2.conv1.weight: [1, 1]
  layer1.2.conv2.weight: [1, 1]
  layer2.0.conv1.weight: [1, 1]
  layer2.0.conv2.weight: [1, 1]
  layer2.0.shortcut.0.weight: [1, 1]
  layer2.1.conv1.weight: [1, 1]
  layer2.1.conv2.weight: [1, 1]
  layer2.2.conv1.weight: [1, 1]
  layer2.2.conv2.weight: [1, 1]
  layer2.3.conv1.weight: [1, 1]
  layer2.3.conv2.weight: [1, 1]
  layer3.0.conv1.weight: [1, 1]
  layer3.0.conv2.weight: [1, 1]
  layer3.0.shortcut.0.weight: [1, 1]
  layer3.1.conv1.weight: [1, 1]
  layer3.1.conv2.weight: [1, 1]
  layer3.10.conv1.weight: [1, 1]
  layer3.10.conv2.weight: [1, 1]
  layer3.11.conv1.weight: [1, 1]
  layer3.11.conv2.weight: [1, 1]
  layer3.12.conv1.weight: [1, 1]
  layer3.12.conv2.weight: [1, 1]
  layer3.13.conv1.weight: [1, 1]
  layer3.13.conv2.weight: [1, 1]
  layer3.14.conv1.weight: [1, 1]
  layer3.14.conv2.weight: [1, 1]
  layer3.15.conv1.weight: [1, 1]
  layer3.15.conv2.weight: [1, 1]
  layer3.16.conv1.weight: [1, 1]
  layer3.16.conv2.weight: [1, 1]
  layer3.17.conv1.weight: [1, 1]
  layer3.17.conv2.weight: [1, 1]
  layer3.18.conv1.weight: [1, 1]
  layer3.18.conv2.weight: [1, 1]
  layer3.19.conv1.weight: [1, 1]
  layer3.19.conv2.weight: [1, 1]
  layer3.2.conv1.weight: [1, 1]
  layer3.2.conv2.weight: [1, 1]
  layer3.20.conv1.weight: [1, 1]
  layer3.20.conv2.weight: [1, 1]
  layer3.21.conv1.weight: [1, 1]
  layer3.21.conv2.weight: [1, 1]
  layer3.22.conv1.weight: [1, 1]
  layer3.22.conv2.weight: [1, 1]
  layer3.3.conv1.weight: [1, 1]
  layer3.3.conv2.weight: [1, 1]
  layer3.4.conv1.weight: [1, 1]
  layer3.4.conv2.weight: [1, 1]
  layer3.5.conv1.weight: [1, 1]
  layer3.5.conv2.weight: [1, 1]
  layer3.6.conv1.weight: [1, 1]
  layer3.6.conv2.weight: [1, 1]
  layer3.7.conv1.weight: [1, 1]
  layer3.7.conv2.weight: [1, 1]
  layer3.8.conv1.weight: [1, 1]
  layer3.8.conv2.weight: [1, 1]
  layer3.9.conv1.weight: [1, 1]
  layer3.9.conv2.weight: [1, 1]
  layer4.0.conv1.weight: [1, 1]
  layer4.0.conv2.weight: [1, 1]
  layer4.0.shortcut.0.weight: [1, 1]
  layer4.1.conv1.weight: [1, 1]
  layer4.1.conv2.weight: [1, 1]
  layer4.2.conv1.weight: [1, 1]
  layer4.2.conv2.weight: [1, 1]
