
# # define partitions for your network
# bn_partitions:
#     - 4
#     - 4
#     - 4
#     - 4
#     - 4
#     - 4
#     - 4
#     - 4
#     - 4
# partitions:
#    conv1.weight:
#      1
#    'layer1.0.conv1.weight': 4
#    'layer1.0.conv2.weight': 4
#    'layer1.0.convShortcut.weight': 4
#    'layer1.1.conv1.weight': 4
#    'layer1.1.conv2.weight': 4
#    'layer1.2.conv1.weight': 4
#    'layer1.2.conv2.weight': 4
#    'layer1.3.conv1.weight': 4
#    'layer1.3.conv2.weight': 4
#    'layer2.0.conv1.weight': 4
#    'layer2.0.conv2.weight': 4
#    'layer2.0.convShortcut.weight': 4
#    'layer2.1.conv1.weight': 4
#    'layer2.1.conv2.weight': 4
#    'layer2.2.conv1.weight': 4
#    'layer2.2.conv2.weight': 4
#    'layer2.3.conv1.weight': 4
#    'layer2.3.conv2.weight': 4
#    'layer3.0.conv1.weight': 4
#    'layer3.0.conv2.weight': 4
#    'layer3.0.convShortcut.weight': 4
#    'layer3.1.conv1.weight': 4
#    'layer3.1.conv2.weight': 4
#    'layer3.2.conv1.weight': 4
#    'layer3.2.conv2.weight': 4
#    'layer3.3.conv1.weight': 4
#    'layer3.3.conv2.weight': 4

# define partitions for your network
bn_partitions:
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
partitions:
   inputs:
     - [1,1,1,1]
   conv1.weight:
     - [1,1,1,1]
   layer1.0.conv1.weight:
     - [1,1,1,1]
   layer1.0.conv2.weight:
     - [1,1,1,1]
   layer1.0.convShortcut.weight:
     - [1,1,1,1]
   layer1.1.conv1.weight:
     - [1,1,1,1]
   layer1.1.conv2.weight:
     - [1,1,1,1]
   layer1.2.conv1.weight:
     - [1,1,1,1]
   layer1.2.conv2.weight:
     - [1,1,1,1]
   layer1.3.conv1.weight:
     - [1,1,1,1]
   layer1.3.conv2.weight:
     - [1,1,1,1]
   layer2.0.conv1.weight:
     - [1,1,1,1]
   layer2.0.conv2.weight:
     - [1,1,1,1]
   layer2.0.convShortcut.weight:
     - [1,1,1,1]
   layer2.1.conv1.weight:
     - [1,1,1,1]
   layer2.1.conv2.weight:
     - [1,1,1,1]
   layer2.2.conv1.weight:
     - [1,1,1,1]
   layer2.2.conv2.weight:
     - [1,1,1,1]
   layer2.3.conv1.weight:
     - [1,1,1,1]
   layer2.3.conv2.weight:
     - [1,1,1,1]
   layer3.0.conv1.weight:
     - [1,1,1,1]
   layer3.0.conv2.weight:
     - [1,1,1,1]
   layer3.0.convShortcut.weight:
     - [1,1,1,1]
   layer3.1.conv1.weight:
     - [1,1,1,1]
   layer3.1.conv2.weight:
     - [1,1,1,1]
   layer3.2.conv1.weight:
     - [1,1,1,1]
   layer3.2.conv2.weight:
     - [1,1,1,1]
   layer3.3.conv1.weight:
     - [1,1,1,1]
   layer3.3.conv2.weight:
     - [1,1,1,1]

maps:
   conv1.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer1.0.conv1.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer1.0.conv2.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer1.0.convShortcut.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer1.1.conv1.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer1.1.conv2.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer1.2.conv1.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer1.2.conv2.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer1.3.conv1.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer1.3.conv2.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer2.0.conv1.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer2.0.conv2.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer2.0.convShortcut.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer2.1.conv1.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer2.1.conv2.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer2.2.conv1.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer2.2.conv2.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer2.3.conv1.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer2.3.conv2.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer3.0.conv1.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer3.0.conv2.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer3.0.convShortcut.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer3.1.conv1.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer3.1.conv2.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer3.2.conv1.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer3.2.conv2.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer3.3.conv1.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
   layer3.3.conv2.weight:
     - [0,1,1,1]
     - [1,0,1,1]
     - [1,1,0,1]
     - [1,1,1,0]
